dist:
  name: otelcollector
  description: OpenTelemetry Collector Distribution built for Netdata
  output_path: ./build

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.130.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.130.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.130.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.130.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.130.0

replaces:
  - go.opentelemetry.io/collector/exporter/otlpexporter => ../../exporter/otlpexporter
